// Code generated by polygen; DO NOT EDIT.
package tests

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
)

var (
	_ IsShape = Circle{}
	_ IsShape = Empty{}
	_ IsShape = (*Group)(nil)
	_ IsShape = (*Polygon)(nil)
	_ IsShape = Rectangle{}
)

// _ShapeDefaultTypeRegistry maps concrete types to their type names
var _ShapeDefaultTypeRegistry = map[reflect.Type]string{
	reflect.TypeOf((*Circle)(nil)).Elem():    "circle",
	reflect.TypeOf((*Empty)(nil)).Elem():     "empty",
	reflect.TypeOf((*Group)(nil)):            "group",
	reflect.TypeOf((*Polygon)(nil)):          "polygon",
	reflect.TypeOf((*Rectangle)(nil)).Elem(): "rectangle",
}

type ShapeDefault struct {
	IsShape
}

func (v ShapeDefault) MarshalJSON() ([]byte, error) {
	if v.IsShape == nil {
		return []byte("null"), nil
	}

	// Marshal the implementation first to get its fields
	implData, err := json.Marshal(v.IsShape)
	if err != nil {
		return nil, fmt.Errorf("polygen: cannot marshal IsShape for ShapeDefault: %v", err)
	}

	if bytes.Equal(implData, []byte("null")) {
		return implData, nil
	}

	typeName, _, err := _ShapeDefaultGetType(v.IsShape)
	if err != nil {
		return nil, fmt.Errorf("polygen: cannot get subtype to marshal for ShapeDefault: %v", err)
	}

	// If it's an empty object, just return discriminator
	if bytes.Equal(implData, []byte("{}")) {
		return []byte(fmt.Sprintf(`{"%s":"%s"}`, "type", typeName)), nil
	}

	// Otherwise, combine discriminator with implementation fields
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf(`{"%s":"%s",`, "type", typeName))
	buf.Write(implData[1:])

	return buf.Bytes(), nil
}

func (v *ShapeDefault) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*v = ShapeDefault{}
		return nil
	}

	var currTypeName string
	var currTypeAsPointer bool

	if v.IsShape != nil {
		var err error
		currTypeName, currTypeAsPointer, err = _ShapeDefaultGetType(v.IsShape)
		if err != nil {
			return fmt.Errorf("polygen: cannot get subtype to unmarshal for ShapeDefault: %v", err)
		}
	}
	_ = currTypeAsPointer // In case of all subtypes being pointers, we must just ignore this

	// First decode just the type field
	typeData := struct {
		TypeName string `json:"type"`
	}{
		TypeName: currTypeName,
	}
	if err := json.Unmarshal(data, &typeData); err != nil {
		return fmt.Errorf("polygen: cannot unmarshal discriminator type for ShapeDefault: %v", err)
	}

	if typeData.TypeName == "" {
		typeData.TypeName = "circle"
	}

	typeName := typeData.TypeName

	var value IsShape

	switch typeName {
	case "circle":
		if currTypeName == "circle" {
			if currTypeAsPointer {
				vv := v.IsShape.(*Circle)
				if err := json.Unmarshal(data, &vv); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Circle for ShapeDefault: %v", err)
				}
				value = vv
			} else {
				vv := v.IsShape.(Circle)
				if err := json.Unmarshal(data, &vv); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Circle for ShapeDefault: %v", err)
				}
				value = vv
			}
		} else {
			var vv Circle
			if err := json.Unmarshal(data, &vv); err != nil {
				return fmt.Errorf("polygen: cannot unmarshal Circle for ShapeDefault: %v", err)
			}
			value = vv
		}
	case "empty":
		if currTypeName == "empty" {
			if currTypeAsPointer {
				vv := v.IsShape.(*Empty)
				if err := json.Unmarshal(data, &vv); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Empty for ShapeDefault: %v", err)
				}
				value = vv
			} else {
				vv := v.IsShape.(Empty)
				if err := json.Unmarshal(data, &vv); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Empty for ShapeDefault: %v", err)
				}
				value = vv
			}
		} else {
			var vv Empty
			if err := json.Unmarshal(data, &vv); err != nil {
				return fmt.Errorf("polygen: cannot unmarshal Empty for ShapeDefault: %v", err)
			}
			value = vv
		}
	case "group":
		var vv *Group
		if currTypeName == "group" {
			vv = v.IsShape.(*Group)
		}
		if err := json.Unmarshal(data, &vv); err != nil {
			return fmt.Errorf("polygen: cannot unmarshal Group for ShapeDefault: %v", err)
		}
		value = vv
	case "polygon":
		var vv *Polygon
		if currTypeName == "polygon" {
			vv = v.IsShape.(*Polygon)
		}
		if err := json.Unmarshal(data, &vv); err != nil {
			return fmt.Errorf("polygen: cannot unmarshal Polygon for ShapeDefault: %v", err)
		}
		value = vv
	case "rectangle":
		if currTypeName == "rectangle" {
			if currTypeAsPointer {
				vv := v.IsShape.(*Rectangle)
				if err := json.Unmarshal(data, &vv); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Rectangle for ShapeDefault: %v", err)
				}
				value = vv
			} else {
				vv := v.IsShape.(Rectangle)
				if err := json.Unmarshal(data, &vv); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Rectangle for ShapeDefault: %v", err)
				}
				value = vv
			}
		} else {
			var vv Rectangle
			if err := json.Unmarshal(data, &vv); err != nil {
				return fmt.Errorf("polygen: cannot unmarshal Rectangle for ShapeDefault: %v", err)
			}
			value = vv
		}
	default:
		return fmt.Errorf("polygen: unknown subtype for ShapeDefault: %s", typeName)
	}

	*v = ShapeDefault{
		IsShape: value,
	}
	return nil
}

func _ShapeDefaultGetType(v IsShape) (name string, asPointer bool, _ error) {
	t := reflect.TypeOf(v)
	typeName, ok := _ShapeDefaultTypeRegistry[t]
	if ok {
		return typeName, false, nil
	}
	// A pointer can be manually used for a value type as it also implements the interface
	if t.Kind() == reflect.Ptr {
		typeName, ok = _ShapeDefaultTypeRegistry[t.Elem()]
		if ok {
			return typeName, true, nil
		}
	}
	return "", false, fmt.Errorf("unknown subtype: %v", t)
}
