// Code generated by polygen; DO NOT EDIT.

//go:build go1.20 && go1.25 && goexperiment.jsonv2

package tests

import (
	"bytes"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
)

func (v Shape) MarshalJSONTo(enc *jsontext.Encoder) error {
	if v.IsShape == nil {
		return enc.WriteValue([]byte("null"))
	}

	// Marshal the implementation first to get its fields
	implData, err := json.Marshal(v.IsShape, enc.Options())
	if err != nil {
		return fmt.Errorf("polygen: cannot marshal IsShape for Shape: %v", err)
	}

	if bytes.Equal(implData, []byte("null")) {
		return enc.WriteValue(implData)
	}

	typeName, _, err := _ShapeGetType(v.IsShape)
	if err != nil {
		return fmt.Errorf("polygen: cannot get subtype to marshal for Shape: %v", err)
	}

	// If it's an empty object, just return discriminator
	if bytes.Equal(implData, []byte("{}")) {
		return enc.WriteValue([]byte(`{"type":"` + typeName + `"}`))
	}

	if len(implData) == 0 || implData[0] != '{' {
		return fmt.Errorf("polygen: expected JSON object for IsShape (%T), got %s", v.IsShape, implData)
	}

	// Otherwise, combine discriminator with implementation fields
	var buf bytes.Buffer
	buf.Grow(len(`{"type":"",`) + len(typeName) + len(implData) - 1)
	buf.WriteString(`{"type":"`)
	buf.WriteString(typeName)
	buf.WriteString(`",`)
	buf.Write(implData[1:])

	return enc.WriteValue(buf.Bytes())
}

func (v *Shape) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	var currTypeName string
	var currTypeAsPointer bool

	if v.IsShape != nil {
		var err error
		currTypeName, currTypeAsPointer, err = _ShapeGetType(v.IsShape)
		if err != nil {
			return fmt.Errorf("polygen: cannot get subtype to unmarshal for Shape: %v", err)
		}
	}
	_ = currTypeAsPointer // In case of all subtypes being pointers, we must just ignore this

	fullData := &struct {
		TypeName string         `json:"type"`
		Data     jsontext.Value `json:",unknown"`
	}{
		TypeName: currTypeName,
		Data:     []byte("{}"),
	}

	if err := json.UnmarshalDecode(dec, &fullData, json.RejectUnknownMembers(false)); err != nil {
		return fmt.Errorf("polygen: cannot unmarshal: %v", err)
	}

	if fullData == nil {
		*v = Shape{}
		return nil
	}

	if fullData.TypeName == "" {
		return fmt.Errorf("polygen: missing discriminator type for Shape")
	}

	typeName := fullData.TypeName

	var value IsShape

	switch typeName {
	case "circle":
		if currTypeName == "circle" {
			if currTypeAsPointer {
				vv := v.IsShape.(*Circle)
				if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Circle for Shape: %v", err)
				}
				value = vv
			} else {
				vv := v.IsShape.(Circle)
				if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Circle for Shape: %v", err)
				}
				value = vv
			}
		} else {
			var vv Circle
			if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
				return fmt.Errorf("polygen: cannot unmarshal Circle for Shape: %v", err)
			}
			value = vv
		}
	case "empty":
		if currTypeName == "empty" {
			if currTypeAsPointer {
				vv := v.IsShape.(*Empty)
				if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Empty for Shape: %v", err)
				}
				value = vv
			} else {
				vv := v.IsShape.(Empty)
				if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Empty for Shape: %v", err)
				}
				value = vv
			}
		} else {
			var vv Empty
			if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
				return fmt.Errorf("polygen: cannot unmarshal Empty for Shape: %v", err)
			}
			value = vv
		}
	case "group":
		var vv *Group
		if currTypeName == "group" {
			vv = v.IsShape.(*Group)
		}
		if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
			return fmt.Errorf("polygen: cannot unmarshal Group for Shape: %v", err)
		}
		value = vv
	case "polygon":
		var vv *Polygon
		if currTypeName == "polygon" {
			vv = v.IsShape.(*Polygon)
		}
		if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
			return fmt.Errorf("polygen: cannot unmarshal Polygon for Shape: %v", err)
		}
		value = vv
	case "rectangle":
		if currTypeName == "rectangle" {
			if currTypeAsPointer {
				vv := v.IsShape.(*Rectangle)
				if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Rectangle for Shape: %v", err)
				}
				value = vv
			} else {
				vv := v.IsShape.(Rectangle)
				if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
					return fmt.Errorf("polygen: cannot unmarshal Rectangle for Shape: %v", err)
				}
				value = vv
			}
		} else {
			var vv Rectangle
			if err := json.Unmarshal(fullData.Data, &vv, dec.Options()); err != nil {
				return fmt.Errorf("polygen: cannot unmarshal Rectangle for Shape: %v", err)
			}
			value = vv
		}
	default:
		return fmt.Errorf("polygen: unknown subtype for Shape: %s", typeName)
	}

	*v = Shape{
		IsShape: value,
	}
	return nil
}
