// Code generated by polygen; DO NOT EDIT.
package tests

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
)

var (
	_ IsShape = Circle{}
	_ IsShape = Empty{}
	_ IsShape = (*Group)(nil)
	_ IsShape = (*Polygon)(nil)
	_ IsShape = Rectangle{}
)

// _ShapeStrictTypeRegistry maps concrete types to their type names
var _ShapeStrictTypeRegistry = map[reflect.Type]string{
	reflect.TypeOf((*Circle)(nil)).Elem():    "circle",
	reflect.TypeOf((*Empty)(nil)).Elem():     "empty",
	reflect.TypeOf((*Group)(nil)).Elem():     "group",
	reflect.TypeOf((*Polygon)(nil)).Elem():   "polygon",
	reflect.TypeOf((*Rectangle)(nil)).Elem(): "rectangle",
}

type ShapeStrict struct {
	IsShape
}

func (v ShapeStrict) MarshalJSON() ([]byte, error) {
	if v.IsShape == nil {
		return []byte("null"), nil
	}

	// Marshal the implementation first to get its fields
	implData, err := json.Marshal(v.IsShape)
	if err != nil {
		return nil, fmt.Errorf("marshaling IsShape implementation: %v", err)
	}

	typeName, err := _ShapeStrictGetType(v.IsShape)
	if err != nil {
		return nil, fmt.Errorf("getting type for ShapeStrict: %v", err)
	}

	// If it's an empty object, just return descriptor
	if string(implData) == "{}" {
		return []byte(fmt.Sprintf("{\"%s\":\"%s\"}", "type", typeName)), nil
	}

	// Otherwise, combine descriptor with implementation fields
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("{\"%s\":\"%s\",", "type", typeName))
	buf.Write(implData[1:])

	return buf.Bytes(), nil
}

func (v *ShapeStrict) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		*v = ShapeStrict{}
		return nil
	}

	var currTypeName string
	if v.IsShape != nil {
		var err error
		currTypeName, err = _ShapeStrictGetType(v.IsShape)
		if err != nil {
			return fmt.Errorf("getting type for existing ShapeStrict: %v", err)
		}
	}

	// First decode just the type field
	typeData := struct {
		Type string `json:"type"`
	}{
		Type: currTypeName,
	}
	if err := json.Unmarshal(data, &typeData); err != nil {
		return fmt.Errorf("unmarshaling ShapeStrict type field: %v", err)
	}

	if typeData.Type == "" {
		return fmt.Errorf("missing type field in JSON for ShapeStrict")
	}

	typeName := typeData.Type

	var value IsShape
	switch typeName {
	case "circle":
		vv := struct {
			Circle
			Type string `json:"type"`
		}{}
		if currTypeName == "circle" {
			vv.Circle = v.IsShape.(Circle)
		}
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&vv); err != nil {
			return fmt.Errorf("unmarshaling ShapeStrict as Circle: %v", err)
		}
		value = vv.Circle
	case "empty":
		vv := struct {
			Empty
			Type string `json:"type"`
		}{}
		if currTypeName == "empty" {
			vv.Empty = v.IsShape.(Empty)
		}
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&vv); err != nil {
			return fmt.Errorf("unmarshaling ShapeStrict as Empty: %v", err)
		}
		value = vv.Empty
	case "group":
		vv := struct {
			*Group
			Type string `json:"type"`
		}{}
		if currTypeName == "group" {
			vv.Group = v.IsShape.(*Group)
		} else {
			vv.Group = new(Group)
		}
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&vv); err != nil {
			return fmt.Errorf("unmarshaling ShapeStrict as Group: %v", err)
		}
		value = vv.Group
	case "polygon":
		vv := struct {
			*Polygon
			Type string `json:"type"`
		}{}
		if currTypeName == "polygon" {
			vv.Polygon = v.IsShape.(*Polygon)
		} else {
			vv.Polygon = new(Polygon)
		}
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&vv); err != nil {
			return fmt.Errorf("unmarshaling ShapeStrict as Polygon: %v", err)
		}
		value = vv.Polygon
	case "rectangle":
		vv := struct {
			Rectangle
			Type string `json:"type"`
		}{}
		if currTypeName == "rectangle" {
			vv.Rectangle = v.IsShape.(Rectangle)
		}
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&vv); err != nil {
			return fmt.Errorf("unmarshaling ShapeStrict as Rectangle: %v", err)
		}
		value = vv.Rectangle
	default:
		return fmt.Errorf("unknown ShapeStrict type: %s", typeName)
	}

	*v = ShapeStrict{
		IsShape: value,
	}
	return nil
}

func _ShapeStrictGetType(v IsShape) (string, error) {
	t := reflect.TypeOf(v)
	// Allows using a pointer as a value
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	typeName, ok := _ShapeStrictTypeRegistry[t]
	if !ok {
		return "", fmt.Errorf("unknown type for ShapeStrict: %v", t)
	}
	return typeName, nil
}
